<SecondScreen>:
    md_bg_color: self.theme_cls.surfaceColor

    MDTopAppBar:
        type: "small"
        pos_hint: {'right': 1.0,'top': 1.0}
        theme_elevation_level: "Custom"
        elevation_level: 5
        theme_shadow_color: "Custom"
        shadow_color: "orange"

        MDTopAppBarLeadingButtonContainer:

            MDActionTopAppBarButton:
                icon: "home-circle"
                on_release: 
                    root.manager.transition.direction = "right"
                    root.manager.current = "ecran_principal"

        MDTopAppBarTitle:
            text: "Interaction avec l'utilisateur"

        MDTopAppBarTrailingButtonContainer:

            MDActionTopAppBarButton:
                icon: "language-python"

    MDBoxLayout:
        orientation: "vertical"  # Donne l'orientation de l'écran
        padding: dp(30)
        spacing: dp(30)

        MDLabel:
            text: root.textHello
            halign: "center"
            font_style: "Display"
            role: "small"
            pos_hint: {'center_x': 0.5,'center_y': 0.5}

        MDTextField:
            id: fieldName  # C'est ici qu'on donne l'ID à rechercher
            mode: "outlined"
            size_hint_x: 0.8
            pos_hint: {'center_x': 0.5,'center_y': 0.5}

            MDTextFieldHintText:
                text: "Entrez votre prénom"

            MDTextFieldHelperText:
                text: "On pourra vous dire bonjour"
                mode: "on_focus"

        MDTextField:
            id: fieldAge  # C'est ici qu'on donne l'ID à rechercher
            mode: "filled"
            size_hint_x: 0.8
            pos_hint: {'center_x': 0.5,'center_y': 0.5}
            input_filter: "int"

            MDTextFieldHintText:
                text: "Entrez votre age"

        MDButton:
            style: "filled"
            pos_hint: {'center_x': 0.5,'center_y': 0.5}
            on_release: root.validateName()

            MDButtonText:
                text: "Envoyer"
