#:import utils kivy.utils
#:set lightText "#0a0c0d"
#:set darkText "#d0d0d0"

<MainScreen>:
    md_bg_color: self.theme_cls.surfaceColor

    MDBottomAppBar:
        theme_elevation_level: "Custom"
        elevation_level: 5
        theme_shadow_color: "Custom"
        shadow_color: "orange"

        MDFabBottomAppBarButton:
            icon: "white-balance-sunny" if app.theme_cls.theme_style == "Light" else "moon-waning-crescent"
            on_release: app.switchThemeStyle()

    MDTopAppBar:
        type: "small"
        pos_hint: {'right': 1.0,'top': 1.0}
        theme_elevation_level: "Custom"
        elevation_level: 5
        theme_shadow_color: "Custom"
        shadow_color: "orange"

        MDTopAppBarLeadingButtonContainer:

            MDActionTopAppBarButton:
                icon: "home-circle"

        MDTopAppBarTitle:
            text: root.textLabel

        MDTopAppBarTrailingButtonContainer:

            MDActionTopAppBarButton:
                icon: "language-python"
                on_release: 
                    root.manager.transition.direction = "left"
                    root.manager.current = "ecran_interaction"

    MDBoxLayout:
        orientation: "vertical"  # Donne l'orientation de l'écran
        padding: "20dp"

        MDBoxLayout:
            orientation: "horizontal"
            padding: dp(20)

            MDFloatLayout:
                size_hint_x: 0.5

                MDButton:
                    style: "filled"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    on_release: root.clickButton()

                    MDButtonText:
                        text: "Bonjour"

            MDFloatLayout:
                size_hint_x: 0.5

                MDButton:
                    style: "elevated"
                    pos_hint: {"center_x": 0.5, "center_y": 0.5}
                    on_release: root.changeTextLabel()
                    theme_elevation_level: "Custom"
                    elevation_level: 5
                    theme_shadow_color: "Custom"
                    shadow_color: "orange"

                    MDButtonText:
                        text: "Maîtrisé"

        MDBoxLayout:
            orientation: "vertical"

            MDLabel:
                text: app.textStyle
                pos_hint: {"center_x": 0.5, "center_y": 0.5}
                halign: "center"
                font_style: "3270" if app.theme_cls.theme_style == "Light" else "hack"
                role: "small"
                theme_text_color: "Custom"
                text_color: "navy" if app.theme_cls.theme_style == "Light" else "greenyellow"
